[package]
name = "tjd_the_junk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tjd_api_response = { path = "../tjd_api_response"}