[package]
name = "tjd_the_drawer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tjd_api = { path = "../tjd_api"}
tjd_the_junk = { path = "../tjd_the_junk"}
strum = "0.24"
strum_macros = "0.24"